name: Publish Extension

on: workflow_dispatch

permissions:
  issues: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |-
          zip -r ${{ github.sha }}.zip src

      - name: Archive zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: ${{ github.sha }}.zip

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.a1 }}" ]; then
            echo "Missing a1";
            exit 1;
          fi
          if [ -z "${{ secrets.a2 }}" ]; then
            echo "Missing a2";
            exit 1;
          fi

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: co-devs

      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}

      - name: Instal tool
        run: echo installing

      - name: Deploy to production
        run: echo deploying
