name: Validate Manifest
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: manifest.json

jobs:
  validate-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON file
        run: jq . manifest.json > /dev/null || (echo "Invalid JSON" && exit 1)
      - name: Validate Required Fields
        run: |
          jq -e '.name and .version and .manifest_version' manifest.json > /dev/null || (echo "Missing required fields in manifest.json" && exit 1)
