name: Validate Manifest
on:
    pull_request:
        types: [review_requested]

jobs:
    validate-yaml:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Validate YAML file
              run: yamllint src/manifest.yml
